### PR TITLE
provide feature

### PR DESCRIPTION
**Pull request by tarsius**

### CODE REVIEW

**Comment by lunaryorn** [comment]
@tarsius Why?

**Comment by tarsius** [comment]
Almost all packages contain a "feature". That's why, when I add a package to the Emacsmirror, I check whether the correct feature is provided. If it is not then that is usually because the author is very new to the game, and after closer inspection I decide that I don't want to mirror the package anyway.

And then there is `ert-runner` which looks like a useful tool. But if you don't want to provide a feature that's okay too, I just cannot mirror it then, because I do not want to add a special case for a single package.

**Comment by lunaryorn** [comment]
@tarsius Respectfully, we are not “new to the game”… and we (@rejeep actually) omitted `provide` for a reason: `provide` implies that it's safe to `require` the file, and `ert-runner.el` is not.  It'll break if `require`d in an interactive Emacs session.  We'd give a false promise, if we added `provide`.

And why should we anyway?  This is clearly a non-interactive tool.  You'd never `require` it anyway.

I don't see how that is related to mirroring, though.  Git doesn't care whether there's `provide` in here or not.  

That said, it's your choice to mirror what and how you want, of course, but I would not like to add a misleading—to say the least, I'd rather say “wrong”—`provide` just to support arbitrary requirements of a particular mirror.

**Comment by tarsius** [comment]
> Respectfully, we are not “new to the game”

Never said you were. Newcomers often don't provide a feature by mistake, that doesn't mean that not providing always is a a mistake. If you don't provide a feature, and if it is by mistake, of course does not make you a beginner in my eyes.

> … and we (@rejeep actually) omitted provide for a reason: provide implies that it's safe to require the file, and ert-runner.el is not. It'll break if required in an interactive Emacs session. We'd give a false promise, if we added provide.
> 
> And why should we anyway? This is clearly a non-interactive tool. You'd never require it anyway.

That's a good argument, and if I had spend a little more time on it I would have noticed. But I have dedicated this day to mirroring an additional 1100 packages, so please forgive me for cutting a corner here.

> I don't see how that is related to mirroring, though. Git doesn't care whether there's provide in here or not.

I am actually building a dependency tree, mainly to detect packages which bundle third-party libraries. Being able to determine which features are provided by a package is essential.

> That said, it's your choice to mirror what and how you want, of course, but I would not like to add a misleading—to say the least, I'd rather say “wrong”—provide just to support arbitrary requirements of a particular mirror.

That's fine. I don't fully agree with it being "wrong" to provide a feature anyway, but I understand your reasoning. I hope you understand that I am not not mirroring your package because of such disagreements, but because it's just more efficient to first mirror the other packages which I can import without having to deal with special cases (however justified they might be).

**Comment by rejeep** [comment]
@tarsius Would like to see that dep-tree. But like @lunaryorn, there's really no point in providing this package.

**Comment by lunaryorn** [comment]
@tarsius As I said, you are free to mirror whatever and however you want.   It doesn't bother me if you don't mirror this repository.

**Pull request closed without merging**
