### PR TITLE
Default reporter is dot, not ert

### PR DESCRIPTION
**Pull request by Fuco1**
There was a typo in the docstring.

### CODE REVIEW

**Comment by rejeep** [comment]
Actually, I think the parens should be removed, not really relevant to that function actually. Agree?

**Comment by Fuco1** [comment]
I don't understand, you mean the parens around the word "default"?  I think it's good for an option to report the default setting in the help output.

**Comment by rejeep** [comment]
Never mind that comment, I realised now that that comment is used when calling `ert-runner -h`.

**Comment by Fuco1** [comment]
cheers!

**Pull request merged**
